/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * GestionStatistics API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { ZonedDateTime } from "./zonedDateTime";

export interface AuditEvent {
  applicationName: string;
  creationDate: ZonedDateTime;
  eventType: string;
  message: string;
}
