/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * gestion_statistics API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Instant } from "./instant";

export interface AuditEvent {
  functionalDomain: string;
  creationDate: Instant;
  eventType: string;
  message: string;
}
