/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * GestionStatistics API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { LocalDate } from "./localDate";

export interface FrequentationStatistique {
  dateDeService: LocalDate;
  nombreDeClients: number;
}
