/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * GestionStatistics API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export interface Plat {
  nom: string;
  nombreDePlatsCommandes: number;
}
