quarkus.application.name=gestion_statistics
quarkus.container-image.name=gestion-statistics

# for Orval generation code
quarkus.smallrye-openapi.store-schema-directory=target/

quarkus.log.category."io.quarkus.flyway.runtime".min-level=DEBUG
quarkus.log.category."io.quarkus.flyway.runtime".level=DEBUG
