/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * salle_priseDeCommande API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Event } from "./event";
import type { Event2 } from "./event2";
import type { Event1 } from "./event1";

/**
 * Generic events
 */
export type Event3 =
  | (Event & {
      type: string;
    })
  | (Event2 & {
      type: string;
    })
  | (Event1 & {
      type: string;
    });
