/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Cuisine_Production API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type EventType = (typeof EventType)[keyof typeof EventType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventType = {
  CommandeAProduire: "CommandeAProduire",
} as const;
