/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * salle_priseDeCommande API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type Event2Type = (typeof Event2Type)[keyof typeof Event2Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Event2Type = {
  PlatAjoute: "PlatAjoute",
} as const;
