/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * CuisineProduction API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Violation } from "./violation";

/**
 * HTTP Validation Problem Response according to RFC9457 and RFC7807
 */
export interface HttpValidationProblem {
  /** A optional URI reference that identifies the problem type */
  type?: string;
  /** A optional, short, human-readable summary of the problem type */
  title?: string;
  /** The HTTP status code for this occurrence of the problem */
  status?: number;
  /** A optional human-readable explanation specific to this occurrence of the problem */
  detail?: string;
  /** A URI reference that identifies the specific occurrence of the problem */
  instance?: string;
  /** List of validation constraint violations that occurred */
  violations?: Violation[];
  [key: string]: unknown;
}
