/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * CuisineProduction API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type PostProductionMarkProductionTermineeBody = {
  id?: string;
};
