/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Cuisine_Production API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Plat } from "./plat";
import type { Status } from "./status";

export interface Production {
  id: string;
  plats: Plat[];
  status: Status;
}
