/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Cuisine_Production API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Production } from "./production";
import type { Event2 } from "./event2";

export interface Response {
  production: Production;
  events: Event2[];
}
