/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Cuisine_Production API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type Status = (typeof Status)[keyof typeof Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status = {
  A_PRODUIRE: "A_PRODUIRE",
  PRODUCTION_TERMINEE: "PRODUCTION_TERMINEE",
} as const;
