/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * CuisineProduction API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

/**
 * Validation constraint violation details
 */
export interface Violation {
  /** The field for which the validation failed */
  field?: string;
  /** Part of the http request where the validation error occurred such as query, path, header, form, body */
  in?: string;
  /** Description of the validation error */
  message?: string;
}
