services:
  postgres:
    image: postgres:17.6-alpine3.22
    labels:
      io.quarkus.devservices.compose.wait_for.logs: .*database system is ready to
        accept connections.*
    restart: always
    ports:
    - '5432'
    environment:
    - POSTGRES_USER=quarkus
    - POSTGRES_PASSWORD=quarkus
    - POSTGRES_DB=quarkus
    command:
    - postgres
    - -c
    - wal_level=logical
    - -c
    - hot_standby=on
    - -c
    - max_wal_senders=10
    - -c
    - max_replication_slots=10
    - -c
    - synchronized_standby_slots=replication_slot
    healthcheck:
      retries: 5
      interval: 10s
      start_period: 10s
      timeout: 5s
      test: [
        CMD,
        pg_isready
      ]
      
    volumes:
    - ./gestion_statistics_idempotency_consumer.sql:/docker-entrypoint-initdb.d/gestion_statistics_idempotency_consumer.sql:ro,z
    - ./salle_prisedecommande_target_consumer.sql:/docker-entrypoint-initdb.d/salle_prisedecommande_target_consumer.sql:ro,z
    - ./cuisine_production_target_consumer.sql:/docker-entrypoint-initdb.d/cuisine_production_target_consumer.sql:ro,z
  kafka:
    image: debezium-for-dev-service/kafka:3.3.1.Final
    labels:
      io.quarkus.devservices.compose.exposed_ports: /tmp/ports
    restart: always
    ports:
    - '9092'
    - '29092'
    environment:
    - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
    - NODE_ID=1
    - CLUSTER_ID=oh-sxaDRTcyAr6pFRbXyzA
    healthcheck:
      retries: 5
      interval: 10s
      start_period: 10s
      timeout: 5s
      test: [
        CMD,
        ./bin/kafka-topics.sh,
        --bootstrap-server,
        'kafka:29092',
        --list
      ]
      
    depends_on:
    - postgres
