quarkus.application.name=SallePriseDeCommande
quarkus.container-image.name=salle-prise-de-commande

quarkus.datasource.jdbc.telemetry=true
# for Orval generation code
quarkus.smallrye-openapi.store-schema-directory=target/

quarkus.native.monitoring=jmxserver
