/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * salle_priseDeCommande API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { NumeroDeTable } from "./numeroDeTable";
import type { DatePriseDeCommande } from "./datePriseDeCommande";

export interface CommandeId {
  numeroDeTableDTO?: NumeroDeTable;
  datePriseDeCommande: DatePriseDeCommande;
}
