/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * salle_priseDeCommande API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Plat } from "./plat";
import type { Status } from "./status";

export interface Commande {
  numeroDeTable: number;
  datePriseDeCommande: number;
  nombreDeConvives: number;
  plats: Plat[];
  status: Status;
}
