/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * SallePriseDeCommande API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { NombreDeConvives } from "./nombreDeConvives";
import type { NumeroDeTable } from "./numeroDeTable";

export type CommencerLaPriseDeCommandeBody = {
  nombreDeConvives?: NombreDeConvives;
  numeroDeTable?: NumeroDeTable;
};
