/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * salle_priseDeCommande API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { CommandeId } from "./commandeId";
import type { NombreDeConvives } from "./nombreDeConvives";
import type { Plat } from "./plat";
import type { Status } from "./status";

export interface Commande {
  commandeId: CommandeId;
  nombreDeConvives: NombreDeConvives;
  plats: Plat[];
  status: Status;
}
