/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * salle_priseDeCommande API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Plat } from "./plat";
import type { Event2Type } from "./event2Type";

export interface Event2 {
  plat: Plat;
  type: Event2Type;
}
