/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * SallePriseDeCommande API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { EventNombreDeConvives } from "./eventNombreDeConvives";
import type { EventType } from "./eventType";

export interface Event {
  nombreDeConvives: EventNombreDeConvives;
  type: EventType;
}
