/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * salle_priseDeCommande API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type Event1Type = (typeof Event1Type)[keyof typeof Event1Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Event1Type = {
  CommandeFinalisee: "CommandeFinalisee",
} as const;
