/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * salle_priseDeCommande API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Event1Type } from "./event1Type";

export interface Event1 {
  type: Event1Type;
}
