/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * SallePriseDeCommande API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type PostPriseDeCommandeCommandIdentifierAjouterPlatBody = {
  nom?: string;
};
