/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * salle_priseDeCommande API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Commande } from "./commande";
import type { Event3 } from "./event3";

export interface Response {
  commande: Commande;
  events: Event3[];
}
