/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * salle_priseDeCommande API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type Status = (typeof Status)[keyof typeof Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status = {
  INCONNU: "INCONNU",
  EN_COURS_DE_PRISE: "EN_COURS_DE_PRISE",
  FINALISEE: "FINALISEE",
} as const;
