/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * salle_priseDeCommande API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type {
  PostPriseDeCommandeCommencerLaPriseDeCommandeBody,
  PostPriseDeCommandeNumeroDeTableAjouterPlatBody,
  Response,
} from "./model";

import { customInstance } from "./mutator/custom-instance";

/**
 * @summary Commencer La Prise De Commande
 */
export const postPriseDeCommandeCommencerLaPriseDeCommande = (
  postPriseDeCommandeCommencerLaPriseDeCommandeBody: PostPriseDeCommandeCommencerLaPriseDeCommandeBody,
) => {
  const formUrlEncoded = new URLSearchParams();
  if (
    postPriseDeCommandeCommencerLaPriseDeCommandeBody.nombreDeConvives !==
    undefined
  ) {
    formUrlEncoded.append(
      `nombreDeConvives`,
      postPriseDeCommandeCommencerLaPriseDeCommandeBody.nombreDeConvives.toString(),
    );
  }
  if (
    postPriseDeCommandeCommencerLaPriseDeCommandeBody.numeroDeTable !==
    undefined
  ) {
    formUrlEncoded.append(
      `numeroDeTable`,
      postPriseDeCommandeCommencerLaPriseDeCommandeBody.numeroDeTable.toString(),
    );
  }

  return customInstance<Response>({
    url: `/priseDeCommande/commencerLaPriseDeCommande`,
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    data: formUrlEncoded,
  });
};

/**
 * @summary Ajouter Plat
 */
export const postPriseDeCommandeNumeroDeTableAjouterPlat = (
  numeroDeTable: number,
  postPriseDeCommandeNumeroDeTableAjouterPlatBody: PostPriseDeCommandeNumeroDeTableAjouterPlatBody,
) => {
  const formUrlEncoded = new URLSearchParams();
  if (postPriseDeCommandeNumeroDeTableAjouterPlatBody.nom !== undefined) {
    formUrlEncoded.append(
      `nom`,
      postPriseDeCommandeNumeroDeTableAjouterPlatBody.nom,
    );
  }

  return customInstance<Response>({
    url: `/priseDeCommande/${numeroDeTable}/ajouterPlat`,
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    data: formUrlEncoded,
  });
};

/**
 * @summary Finaliser La Commande
 */
export const postPriseDeCommandeNumeroDeTableFinaliserLaCommande = (
  numeroDeTable: number,
) => {
  return customInstance<Response>({
    url: `/priseDeCommande/${numeroDeTable}/finaliserLaCommande`,
    method: "POST",
  });
};

/**
 * @summary Register
 */
export const getSseStream = () => {
  return customInstance<void>({ url: `/sse/stream`, method: "GET" });
};

export type PostPriseDeCommandeCommencerLaPriseDeCommandeResult = NonNullable<
  Awaited<ReturnType<typeof postPriseDeCommandeCommencerLaPriseDeCommande>>
>;
export type PostPriseDeCommandeNumeroDeTableAjouterPlatResult = NonNullable<
  Awaited<ReturnType<typeof postPriseDeCommandeNumeroDeTableAjouterPlat>>
>;
export type PostPriseDeCommandeNumeroDeTableFinaliserLaCommandeResult =
  NonNullable<
    Awaited<
      ReturnType<typeof postPriseDeCommandeNumeroDeTableFinaliserLaCommande>
    >
  >;
export type GetSseStreamResult = NonNullable<
  Awaited<ReturnType<typeof getSseStream>>
>;
