/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * salle_priseDeCommande API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type {
  PostPriseDeCommandeCommandIdentifierAjouterPlatBody,
  PostPriseDeCommandeCommencerLaPriseDeCommandeBody,
  Response,
} from "./model";

import { customInstance } from "./mutator/custom-instance";

/**
 * @summary Register
 */
export const getNotifierSseStream = () => {
  return customInstance<void>({ url: `/notifier/sse/stream`, method: "GET" });
};

/**
 * @summary Commencer La Prise De Commande
 */
export const postPriseDeCommandeCommencerLaPriseDeCommande = (
  postPriseDeCommandeCommencerLaPriseDeCommandeBody: PostPriseDeCommandeCommencerLaPriseDeCommandeBody,
) => {
  const formUrlEncoded = new URLSearchParams();
  if (
    postPriseDeCommandeCommencerLaPriseDeCommandeBody.nombreDeConvives !==
    undefined
  ) {
    formUrlEncoded.append(
      `nombreDeConvives`,
      postPriseDeCommandeCommencerLaPriseDeCommandeBody.nombreDeConvives.toString(),
    );
  }
  if (
    postPriseDeCommandeCommencerLaPriseDeCommandeBody.numeroDeTable !==
    undefined
  ) {
    formUrlEncoded.append(
      `numeroDeTable`,
      postPriseDeCommandeCommencerLaPriseDeCommandeBody.numeroDeTable.toString(),
    );
  }

  return customInstance<Response>({
    url: `/priseDeCommande/commencerLaPriseDeCommande`,
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    data: formUrlEncoded,
  });
};

/**
 * @summary Ajouter Plat
 */
export const postPriseDeCommandeCommandIdentifierAjouterPlat = (
  commandIdentifier: string,
  postPriseDeCommandeCommandIdentifierAjouterPlatBody: PostPriseDeCommandeCommandIdentifierAjouterPlatBody,
) => {
  const formUrlEncoded = new URLSearchParams();
  if (postPriseDeCommandeCommandIdentifierAjouterPlatBody.nom !== undefined) {
    formUrlEncoded.append(
      `nom`,
      postPriseDeCommandeCommandIdentifierAjouterPlatBody.nom,
    );
  }

  return customInstance<Response>({
    url: `/priseDeCommande/${commandIdentifier}/ajouterPlat`,
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    data: formUrlEncoded,
  });
};

/**
 * @summary Finaliser La Commande
 */
export const postPriseDeCommandeCommandIdentifierFinaliserLaCommande = (
  commandIdentifier: string,
) => {
  return customInstance<Response>({
    url: `/priseDeCommande/${commandIdentifier}/finaliserLaCommande`,
    method: "POST",
  });
};

export type GetNotifierSseStreamResult = NonNullable<
  Awaited<ReturnType<typeof getNotifierSseStream>>
>;
export type PostPriseDeCommandeCommencerLaPriseDeCommandeResult = NonNullable<
  Awaited<ReturnType<typeof postPriseDeCommandeCommencerLaPriseDeCommande>>
>;
export type PostPriseDeCommandeCommandIdentifierAjouterPlatResult = NonNullable<
  Awaited<ReturnType<typeof postPriseDeCommandeCommandIdentifierAjouterPlat>>
>;
export type PostPriseDeCommandeCommandIdentifierFinaliserLaCommandeResult =
  NonNullable<
    Awaited<
      ReturnType<typeof postPriseDeCommandeCommandIdentifierFinaliserLaCommande>
    >
  >;
