/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * gestion_statistics API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type {
  AuditEvent,
  CommandeStatistique,
  FrequentationStatistique,
} from "./model";

import { customInstance } from "./mutator/custom-instance";

/**
 * @summary Events
 */
export const getEvents = () => {
  return customInstance<AuditEvent[]>({ url: `/events`, method: "GET" });
};

/**
 * @summary Register
 */
export const getNotifierSseStream = () => {
  return customInstance<void>({ url: `/notifier/sse/stream`, method: "GET" });
};

/**
 * @summary List
 */
export const getStatistiquesCommandes = () => {
  return customInstance<CommandeStatistique[]>({
    url: `/statistiques/commandes`,
    method: "GET",
  });
};

/**
 * @summary List
 */
export const getStatistiquesFrequentation = () => {
  return customInstance<FrequentationStatistique[]>({
    url: `/statistiques/frequentation`,
    method: "GET",
  });
};

export type GetEventsResult = NonNullable<
  Awaited<ReturnType<typeof getEvents>>
>;
export type GetNotifierSseStreamResult = NonNullable<
  Awaited<ReturnType<typeof getNotifierSseStream>>
>;
export type GetStatistiquesCommandesResult = NonNullable<
  Awaited<ReturnType<typeof getStatistiquesCommandes>>
>;
export type GetStatistiquesFrequentationResult = NonNullable<
  Awaited<ReturnType<typeof getStatistiquesFrequentation>>
>;
