/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Cuisine_Production API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type {
  PostProductionMarkProductionTermineeBody,
  Response,
} from "./model";

import { customInstance } from "./mutator/custom-instance";

/**
 * @summary Mark Production Terminee
 */
export const postProductionMarkProductionTerminee = (
  postProductionMarkProductionTermineeBody: PostProductionMarkProductionTermineeBody,
) => {
  const formUrlEncoded = new URLSearchParams();
  if (postProductionMarkProductionTermineeBody.id !== undefined) {
    formUrlEncoded.append(`id`, postProductionMarkProductionTermineeBody.id);
  }

  return customInstance<Response>({
    url: `/production/markProductionTerminee`,
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    data: formUrlEncoded,
  });
};

/**
 * @summary Stream Events
 */
export const getSseStream = () => {
  return customInstance<void>({ url: `/sse/stream`, method: "GET" });
};

export type PostProductionMarkProductionTermineeResult = NonNullable<
  Awaited<ReturnType<typeof postProductionMarkProductionTerminee>>
>;
export type GetSseStreamResult = NonNullable<
  Awaited<ReturnType<typeof getSseStream>>
>;
