/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Cuisine_Production API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type {
  PostProductionMarkProductionTermineeBody,
  Response,
} from "./model";

import { customInstance } from "./mutator/custom-instance";

/**
 * @summary Register
 */
export const getNotifierSseStream = () => {
  return customInstance<void>({ url: `/notifier/sse/stream`, method: "GET" });
};

/**
 * @summary Mark Production Terminee
 */
export const postProductionMarkProductionTerminee = (
  postProductionMarkProductionTermineeBody: PostProductionMarkProductionTermineeBody,
) => {
  const formUrlEncoded = new URLSearchParams();
  if (postProductionMarkProductionTermineeBody.id !== undefined) {
    formUrlEncoded.append(`id`, postProductionMarkProductionTermineeBody.id);
  }

  return customInstance<Response>({
    url: `/production/markProductionTerminee`,
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    data: formUrlEncoded,
  });
};

export type GetNotifierSseStreamResult = NonNullable<
  Awaited<ReturnType<typeof getNotifierSseStream>>
>;
export type PostProductionMarkProductionTermineeResult = NonNullable<
  Awaited<ReturnType<typeof postProductionMarkProductionTerminee>>
>;
